name: Bug report
description: Let us know about crashes or existing functionality not working like it should.
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have used the search function to see if someone else has already submitted the same bug report.
          required: true
        - label: I will describe the problem with as much detail as possible.
          required: true
  - type: input
    id: version
    attributes:
      label: App version
      description: What's the "latest version" changes all the time, so we need the exact version number. You can find it inside the app under *Settings → About*.
      placeholder: x.yyy
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Where did you get the app from?
      multiple: false
      options:
        - Google Play
        - F-Droid
        - Other
  - type: input
    id: android_version
    attributes:
      label: Android version
      description: Please mention if you are using a custom ROM!
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device model
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. etc.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: After following the steps, what did you think K-9 Mail would do?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What did K-9 Mail do instead? Screenshots might help. Usually, you can take a screenshot by pressing *Power* + *Volume down* for a few seconds.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
